// Generated by CoffeeScript 1.12.5
(function() {
  $(function() {
    return app.initialize();
  });

  window.app = {
    votes: [0, 0, 0, 0],
    staffs: {
      0: 'deguchi',
      1: 'sasaki',
      2: 'dei',
      3: 'matsuno'
    },
    initialize: function() {
      return this.setBind();
    },
    setBind: function() {
      var self;
      self = this;
      $('.staff_btn').on('click', function() {
        var number;
        number = Number($(this).data('number'));
        return self.votes[number]++;
      });
      $('.result_btn').on('click', function() {
        var _result;
        _result = '';
        _.each(self.votes, function(val) {
          return _result += "[" + val + "] ";
        });
        $('#result').text(_result);
        return $('.drum_btn').css({
          'display': 'block'
        });
      });
      return $('.drum_btn').on('click', function() {
        var _mvp;
        _mvp = self.staffs[_.indexOf(self.votes, _.max(self.votes))];
        console.log(_mvp);
        $('.container-fluid').html('<div style="font-size:50px;">集計中...</div>');
        $('#drum')[0].play();
        return setTimeout((function(_this) {
          return function() {
            return $('.container-fluid').html("<img src=\"image/" + _mvp + ".jpg\" style=\"width:100%;\">");
          };
        })(this), 6000);
      });
    }
  };

}).call(this);
